### ISSUE TITLE
[Feature] Upload multiple images to gallery in one go and tag them

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/MyFamilyRoot#103]
Disabled for the moment and can only upload one at a time.

Some odd error happens with multiple files.

**Comment by JustinWingChungHui** [comment]
Changed this to a feature

**Comment by JustinWingChungHui** [comment]
Probably easier as a native app interface

**Comment by szech** [comment]
Too difficult to implement with js library?

i imagine the difficulty here is finding something that plays equally
nicely on mobile and desktop....
Too fiddly to implement 2 libraries and serve them up independently?


================================

<https://twitter.com/captainszechwan>
<https://www.songkick.com/users/captainszechwan>
<http://www.last.fm/user/CaptainSzechwan>

On 18 January 2016 at 11:27, Justin Wing Chung Hui <notifications@github.com

**Comment by JustinWingChungHui** [comment]
I think it requires some js grunt work!

**Comment by JustinWingChungHui** [comment]
Ability to share from WhatsApp etc is a bigger need.  So would make sense to work on multiple native app uploaded first
