### ISSUE TITLE
[Feature] Gallery location -> geo-tags

### ISSUE THREAD

**Issue by szech** [JustinWingChungHui/MyFamilyRoot#125]
- Add a new field to Gallery: location
- Set this on photos that are not geo-tagged (so instead of being at 0,0 photos can at least be put in a general location)
- Leave geo-tagged photos with their tags intact.

**Comment by JustinWingChungHui** [comment]
It should be on all photos, because geotagging may be inaccurate (e.g. a mobile takes the coordinates of nearest mast if no gps found)

**Comment by szech** [comment]
i presumed that you would want to keep the existing geotags - you could
have taken the pictures on a cruise, for instance.


================================
<https://twitter.com/#!/captainszechwan>
<http://www.last.fm/user/captainszechwan>
<http://www.songkick.com/users/captainszechwan>
