### ISSUE TITLE
[Feature] Expand Family tree view

### ISSUE THREAD

**Issue by szech** [JustinWingChungHui/MyFamilyRoot#127]
For example, i would like to start at myself, and then show the layer above my parents.
Or maybe expand it horizontally to show cousins and aunts & uncles.
Or expand downwards to show children.

not sure if we would want to do it at the "tree level" (for all visible ppl) or per person (with buttons on each person).

**Comment by JustinWingChungHui** [comment]
Would require to move to a single page application architecture and load tree data over AJAX.

A big job!

**Comment by JustinWingChungHui** [comment]
Move to rendering tree in javascript done.  Need to mock up some expansion ui

**Comment by JustinWingChungHui** [comment]
Closing this as current UI is pretty responsive
