### ISSUE TITLE
[Feature] Link to show gallery photo without tags

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/MyFamilyRoot#132]

**Comment by JustinWingChungHui** [comment]
The link should send a person to a gallery showing just pictures of themselves with lightbox opening up on the correct image automatically
http://visuallightbox.com/rq/automatically-open-the-lightbox-popup-upon-opening-the-page-r.html

**Comment by szech** [comment]
Alternative suggestion - only show the lightbox when the user mouses over
(or clicks or touches) on the photo?
(hopefully it will play well on phones)

Not sure how this compares with the alternative gallery view in terms of
effort / work needed
