### ISSUE TITLE
[Feature] Language of new person should default to language of existing relative

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/MyFamilyRoot#154]
E.g.  if mother's language is French, then adding a relation to the mother should default to language French in the UI

**Comment by szech** [comment]
Agreed in principle.
There is an argument that this might not work well for bilingual couples or
ex-pats.

Eg. Hans and Maria from Norway move to France and raise a son.
If the son joins in French, he might like the option to add his parents in
Norwegian.

Could do this with a box in the invite dialog? The box defaults to the
language of the user, but he can select a different language for the
invite.

Feel free to mark this as a low priority improvement.
