### ISSUE TITLE
[Bug] Photoswipe gallery opens previous image after close

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/MyFamilyRoot#213]
Click on an image in gallery
Close photoswipe
Click on another image
Previous image is displayed

**Comment by JustinWingChungHui** [comment]
Finally!!!!!

**Comment by szech** [comment]
Haweh! :D

**Comment by JustinWingChungHui** [comment]
Took me bloody ages to work out that one!  Photoswipe adds stuff to the URL, which it then doesn't clear and rereads when you instantiate it again.
