### ISSUE TITLE
Add brute force password protection 

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/MyFamilyRoot#24]
Use https://github.com/django-pci/django-axes?

**Comment by szech** [comment]
How will we deal with multiple failures on the same account from different
ip addresses?

Granted, I could legitimately fail on my desktop computer and then try my
phone or some other device.
It seems that you would want a limit to the total number of failed attempts
on account to deal with distributed brute force attacks?

I think we should think about it, but after your suggestion is implemented.

**Comment by JustinWingChungHui** [comment]
Doesn't bloody work!

**Comment by JustinWingChungHui** [comment]
So it works for the admin.  Need to find out how to call the function for the normal login page

**Comment by JustinWingChungHui** [comment]
Maybe I can make it work and contribute!

**Comment by JustinWingChungHui** [comment]
Got it to work by calling the methods directly.  Pretty cool, it shows you who has logged in, which ip and what browser they used
