### ISSUE TITLE
Prevent navigation using the page address to unrelated person 

### ISSUE THREAD

**Issue by szech** [JustinWingChungHui/MyFamilyRoot#26]
Currently, we have the page address linked directly to the person id. eg https://www.okkindred.com/person=3
We need to think about obfuscating this (or making it hidden to the user) to prevent you from navigating to a profile from outside your own family. Possibly there are 2 related problems here? 
- person id in address bar
- navigation to unrelated person

**Comment by JustinWingChungHui** [comment]
I think the id in the address is fine.  We just need to not allowed unauthorised access from other families.  We should use a decorator like the @login_required (https://docs.djangoproject.com/en/1.7/topics/auth/default/#the-login-required-decorator) on each of the views
To control this, so it checks the users family against the person_id and return a 404 if they don't match

**Comment by JustinWingChungHui** [comment]
added a @same_family_required decorator
