### ISSUE TITLE
Geocoding Address

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/MyFamilyRoot#4]
Need creation of longitude and latitude given address

**Comment by JustinWingChungHui** [comment]
Longitude/Latitude easy! http://geopy.readthedocs.org/en/1.7.0/

**Comment by JustinWingChungHui** [comment]
Google Usage limit Free:
2,500 requests per 24 hour period. 
5 requests per second. 

Would it be worth setting up a Baidu account to target China better?
https://github.com/geopy/geopy/blob/master/geopy/geocoders/baidu.py

**Comment by szech** [comment]
in the short term it's probably a good idea to use some existing services,
in the long run it might be better to develop our own map server using
openstreetmap data, and then make it look really sexy with Mapbox

server: http://switch2osm.org/serving-tiles/
style: http://wiki.openstreetmap.org/wiki/Mapbox

i sense this is a whole lovely can of worms, lots of potential here.
https://www.mapbox.com/industries/social/



================================
<https://twitter.com/#!/captainszechwan>
<http://www.last.fm/user/captainszechwan>
<http://www.songkick.com/users/captainszechwan>
