### ISSUE TITLE
[Feature] Allow new signups

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/MyFamilyRoot#56]
Post Beta!

Use re-captcha?

**Comment by szech** [comment]
I don't particularly like them, but there are pros and cons.

+
Prevent spam
Easy to implement?

-
Annoying
Bad for internationalisation? (i.e non-western alphabet support?)

Would prefer to use googles new "I'm not a robot" captcha, but the text
can't be changed on that.

**Comment by JustinWingChungHui** [comment]
Yeah that's what I meant by re-captcha
https://developers.google.com/recaptcha/

**Comment by JustinWingChungHui** [comment]
You can try it out here: https://alastairc.ac/testing/recaptcha-test.html
- It doesn't work all the time on desktop
- It doesn't work at all on mobile devices

Google FAIL

**Comment by JustinWingChungHui** [comment]
Interesting... 
http://webaim.org/blog/spam_free_accessible_forms/
http://www.sitepoint.com/captcha-alternatives/

**Comment by JustinWingChungHui** [comment]
Available privately
