### ISSUE TITLE
Google maps is not accessible in China over secure connection

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/MyFamilyRoot#64]
https://developers.google.com/maps/faq#china_ws_access

Well wtf should we do here?  We can't load partially over http and https as it is massively insecure.

Switch to another service?

Well this is a bit of a face palm moment...

**Comment by szech** [comment]
Didn't we discuss using Baidu?

**Comment by JustinWingChungHui** [comment]
Might need some help deciphering their API
http://developer.baidu.com/map/index.php?title=%E9%A6%96%E9%A1%B5


On Tue, 3 Mar 2015, at 10:56 PM, Adrian wrote:
> Didn't we discuss using Baidu?
>
On 3 Mar 2015 02:10, "Justin Wing Chung Hui" <notifications@github.com>
>
wrote:
>
>
> https://developers.google.com/maps/faq#china_ws_access
>
>
>
> Well wtf should we do here? We can't load partially over http and
> https as
>
> it is massively insecure.
>
>
>
> Switch to another service?
>
>
>
> —
>  > Reply to this email directly or view it on GitHub
>
> <https://github.com/JustinWingChungHui/MyFamilyRoot/issues/64>.
>
>
> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/JustinWingChungHui/MyFamilyRoot/issues/64#issuecomment-77057306

**Comment by szech** [comment]
Or some alternative source that is derived from open street map?

**Comment by szech** [comment]
Not sure if applicable to us, but maybe relevant

https://www.drupal.org/project/baidu_map

**Comment by JustinWingChungHui** [comment]
Baidu map is limited to mainland China

**Comment by JustinWingChungHui** [comment]
Open Street map could work....

**Comment by JustinWingChungHui** [comment]
ok switched it to use https://www.mapbox.com/.
It allows 50000 free map views per month https://www.mapbox.com/plans/

And it works over https behind the Great Firewall of China http://www.websitepulse.com/help/testtools.china-test.html
