### ISSUE TITLE
[Feature] Translation work

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/MyFamilyRoot#7]
Chinese, polish, Finnish, simplified Chinese.

**Comment by JustinWingChungHui** [comment]
use this?
https://github.com/mbi/django-rosetta

**Comment by szech** [comment]
So if I understand correctly what it is:
- it reads our English label file
- ...and makes a nice form to write in the translations for each language
-...  And we can can get auto-suggestions if we sign up to yandex or azure

Sounds good to me.

**Comment by JustinWingChungHui** [comment]
It looks like this got updated to be compatible with Django 1.7 16 days ago.  :+1:

**Comment by JustinWingChungHui** [comment]
OK I have put through a google & yandex translated versions.  They seem to work.

Need Hilson, Kati and Ola to have a look
