### ISSUE TITLE
[Bug] Translation does not allow for gender endings

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/MyFamilyRoot#74]
Aaaaargh!!!!!
...and we have 3 genders
e.g.
Welcome =>
Bienvenido
or
Bienvenida

**Comment by szech** [comment]
aw shit.


================================
<https://twitter.com/#!/captainszechwan>
<http://www.last.fm/user/captainszechwan>
<http://www.songkick.com/users/captainszechwan>

**Comment by JustinWingChungHui** [comment]
Will need to store gender on user model
