### ISSUE TITLE
Improve contrast between hyperlink and profile background in tree view

### ISSUE THREAD

**Issue by szech** [JustinWingChungHui/MyFamilyRoot#75]
when mousing over / selecting my own profile in the tree view, the name text turns white and is quite legible. however, for my relatives, the hyperlink text is not as clear because the blue text does not show up as well against the green / blue background.

**Comment by JustinWingChungHui** [comment]
Make the blue green background lighter or make text white?

**Comment by szech** [comment]
Not sure.
Which ever looks better?

Probably white text will look clearer, but we should make sure it still
looks like a navigation.

Bold text might also help?

I have been a bit vague because there isn't a straight answer here.
