### ISSUE TITLE
[Feature] Maps view should be able to combine geographically close profiles into the same popup.

### ISSUE THREAD

**Issue by szech** [JustinWingChungHui/MyFamilyRoot#77]
This will prevent icons from obscuring nearby relatives. e.g. Hong Kong
can see an example here: http://www.wienerlibrary.co.uk/interactivemap

this should also be able to separate them when zooming in closer, and recombine when zooming out.

**Comment by JustinWingChungHui** [comment]
Will need to change the architecture to an ajax request.  Proabably a good idea in the long run.
First load of map would be slower though as it would have two requests instead of one.
