### ISSUE TITLE
[Bug] Anchor tags don't work on Chrome for Android tablets 

### ISSUE THREAD

**Issue by szech** [JustinWingChungHui/MyFamilyRoot#8]
On the tree view, none of the anchor refs function properly on touch event

**Comment by JustinWingChungHui** [comment]
So far only a problem for Chrome on Samsung Tablet
It works on:
- Stock Android browser
- Firefox Android
- Chrome on phones
- All desktop browsers using mouse
- Safari on iPhone
- Safari on iPad

**Comment by szech** [comment]
How about Chrome for ipad?

**Comment by JustinWingChungHui** [comment]
Just checked.  It works for Chrome on iPad.  However dragging does not work for IE touch!

**Comment by JustinWingChungHui** [comment]
Internet Exploder...

**Comment by szech** [comment]
D:

**Comment by szech** [comment]
managed to get remote debug working for chrome.... (swearing was involved)
i have the impression that when you tap on the profile button in the tree
view, jquery/touchpunch interprets this as a draggable event on the parent
div (profile box) instead of invoking a click on the button.

this causes the button to be unresponsive.

any chance we can investigate more at the weekend?



possibly relevant:
http://stackoverflow.com/questions/12215096/using-tap-events-with-twitter-bootstrap



================================
<https://twitter.com/#!/captainszechwan>
<http://www.last.fm/user/captainszechwan>
<http://www.songkick.com/users/captainszechwan>

**Comment by JustinWingChungHui** [comment]
Yeah sure

**Comment by JustinWingChungHui** [comment]
Frozen the drag ability for the moment as tree view is rendered pretty reasonably

**Comment by szech** [comment]
no problem with the profile button on Chrome for Android tablets now.

#winning


================================
<https://twitter.com/#!/captainszechwan>
<http://www.last.fm/user/captainszechwan>
<http://www.songkick.com/users/captainszechwan>
