### ISSUE TITLE
[Feature] Extra social fields to add to person model

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/MyFamilyRoot#90]
Facebook
Skype
Twitter
Weibo
renren

Any others?

**Comment by szech** [comment]
Linked in? (cringe)

Maybe just some kind of "other" field?

**Comment by JustinWingChungHui** [comment]
Maybe its worth adding in Entity Value Attributes so people can add whatever
http://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model
https://eav-django.readthedocs.org/en/latest/#

**Comment by JustinWingChungHui** [comment]
I've added a load for the moment.  We can always add more if requested
